// eslint-disable-next-line no-unused-vars
const testPosts = [
  {
    id: 1,
    content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
    imageUrl: 'https://s1.1zoom.ru/big0/365/321125-alexfas01.jpg',
    author: '@Daria',
    createdAt: new Date('2020-03-13T13:03:00'),
    likes: [],
    hashTags: [
      'dasha',
    ],
  },
  {
    id: 2,
    content: 'Maison Valentino was founded in 1960 by Valentino Garavani & Giancarlo Giammetti. The Creative Direction as of July 7th 2016 was appointed to Pierpaolo Piccioli.',
    author: '@MaisonValentino',
    createdAt: new Date('2020-02-10T17:03:00'),
    likes: [
      {
        id: 1,
      },
    ],
    hashTags: [],
  },
  {
    id: 3,
    content: 'Treat yourself! Starting today, Feb. 29, through March 9, redeem your $20 reward card on a $50 purchase. The Creative Direction as of July 7th 2016 was appointed to Pierpaolo Piccioli.',
    author: '@VictoriasSecret',
    createdAt: new Date('2020-02-09T19:03:00'),
    likes: [],
    hashTags: [],
  },
  {
    id: 4,
    content: 'A new perspective. The upside-down headbands, worn beneath the decoratively woven buns, were the beauty highlight of the Fashion Show.',
    author: '@Fendi',
    createdAt: new Date('2020-02-08T20:03:00'),
    likes: [],
    hashTags: [],
  },
  {
    id: 5,
    content: 'A tailored jacket with an extended tail drape and satin lapels, worn with black wool silk trousers and a white cotton poplin shirt with an extended tail drape and triangular lace trim.',
    author: '@McQueen',
    createdAt: new Date('2020-02-07T21:03:00'),
    likes: [],
    hashTags: [],
  },
  {
    id: 6,
    content: 'A pop of color. Explore the Dior Spring Summer 2020 campaign, shot by Steven Meisel featuring Adriana Lima and Joan Smalls and experience the latest theme of the Dior Spring Summer 2020 collection: The Pastel Army.',
    author: '@Dior',
    createdAt: new Date('2020-02-08T22:20:00'),
    likes: [],
    hashTags: [],
  },
  {
    id: 7,
    content: 'Inside a circular transparent structure in the middle of the space, Gucci’s design team, dressed in grey uniforms with labels that read (Dream Maker), dressed 60 models.',
    author: '@Gucci',
    createdAt: new Date('2020-02-06T23:23:00'),
    likes: [],
    hashTags: [],
  },
  {
    id: 8,
    content: 'The everyday is corrupted by glamour, forms and functions challenged, shifted from practical to aesthetic. March 3rd at 10.30 am Paris time. Film directed by Inez & Vinoodh.',
    author: '@Prada',
    createdAt: new Date('2020-02-05T23:50:00'),
    likes: [],
    hashTags: [],
  },
  {
    id: 9,
    content: 'Casually chic. One of the new Twist bags adds a colorful shoulder strap for a laid-back touch. March 3rd at 10.30 am Paris time. Film directed by Inez & Vinoodh.',
    author: '@LouisVuitton',
    createdAt: new Date('2020-02-04T20:03:00'),
    likes: [],
    hashTags: [],
  },
  {
    id: 10,
    content: 'The Fall-Winter 2020/21 Ready-to-Wear collection will be unveiled tomorrow. Live from Paris on Twitter, March 3rd at 10.30 am Paris time. Film directed by Inez & Vinoodh. Starring Margaret Qualley.',
    author: '@CHANEL',
    createdAt: new Date('2019-02-08T20:03:00'),
    likes: [],
    hashTags: [],
  },
];
